import "./globals.css";
import type { Metadata } from "next";
import { Inter, Orbitron, Montserrat, Roboto } from "next/font/google";
import { TrpcProvider } from "./_trpc/Trpcprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <TrpcProvider>
        <body className={inter.className}>{children}</body>
      </TrpcProvider>
    </html>
  );
}
